### PR TITLE
updating location calls the addLocationFromAPI func in contentviewmodel

### PR DESCRIPTION
**Pull request by alsheikha**
- FOR NOW place is being added as place_id, this can be changed pretty easily once we have a good way of getting place name (places API implementation or creating a dictionary of Carleton addresses)
- Duplicate issue still exists.... API has been overhauled and we're having the same issue. calling API using "Get Location" button in-app will update our data tab, but new entries are being added twice

### CODE REVIEW

**Review by Bottigerd — CHANGES_REQUESTED** [review]
I think I found the duplication issue. In ContentView, remove line 20, `viewModel.updateDisplay()'. startUpdatingLocation() will fetch location and restart the 50 meter count for auto updating. I think I'm the one who did this so I'm sorry.  Everything else looks great! Please @ me on slack once you've done this because then I'll approve. (I'd make the change myself since it's so small but then I can't approve since I'm a collaborator on the branch).

My only other note is why not make the place name in the database the returned address in the API. The returned address will be the Carleton place name once Silas has the dictionary made. The address incorporates what's returned from the places API in that same function updateAddress().

**Review by Bottigerd — APPROVED** [review]
Looks good, thank you!

**Review by jamesmarlin — CHANGES_REQUESTED** [review]
The get location button is not actually calling the API to get the location (no dot appears when loading simulators).

**Comment by Bottigerd** [comment]
> The get location button is not actually calling the API to get the location (no dot appears when loading simulators).

@jamesmarlin Do you have the config.json in your directory or a location set on the simulator? For me, the button is calling the API and centering the map on the current location where the dot is.

**Comment by jamesmarlin** [comment]
We used the config.json file and tried it again. It works on the lab macs, but we found that it duplicates the API calls and seems to only work on IOS 15.5.

**Review by kevinpkw19 — COMMENTED** [review]
only duplicates it once this time though

**Review by SilasZhao — APPROVED** [review]

**Pull request merged**
