### PR TITLE
Implementing core data nuke button

### PR DESCRIPTION
**Pull request by kittyTyree**
Added a button on the data tab that allows you to delete all of the core data entities. It then clears them from view. It has a popup alert that makes sure you really want to be clearing all of your data. Also side note, I had my min ios deployment to 15.2 because of my simulator, but I committed the file on accident so I went back in and changed it so it doesn't screw with the main file (ergo 15.5 adjustment commit).

### CODE REVIEW

**Comment by kevinpkw19** [comment]
Can you close this one and submit a PR with the latest commit? Added some small bugfixes to old code that shouldnt interfere with the nuke but just want to get it through now

**Comment by kittyTyree** [comment]
Closed/reopened pr to include Kevin's changes without realizing they showed up on their own... carry on

**Review by Bottigerd — APPROVED** [review]
Nuke button works for me :)

**Review by jayti-a — APPROVED** [review]
It works for me!

**Pull request merged**
